print(chr(34),end="")
print("Ro'b'er	to\/",end="")
print(chr(34))
print("(._.) ( l: ) ( .-. ) ( :l ) (._.)")
print("(^_-) (-_-) (-_^)")
print("(", end="")
print(chr(34),end="")
print(chr(95),end="")
print(chr(34),end="")
print(") ('.')")